FROM smvanveen/computer-vision:20161109143812

# extra packages:
# libeigen3-dev: for eos: 3D morphable face model fitting library.
RUN apt-get install -y \
    libeigen3-dev \
    libgoogle-glog-dev \
    libatlas-base-dev \
    libeigen3-dev

WORKDIR /libs
RUN git clone https://ceres-solver.googlesource.com/ceres-solver
RUN (cd ceres-solver; mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..)
RUN (cd ceres-solver/build; make -j3; make install)

ENV PYTHONPATH=/usr/local/eos/bin/:$PYTHONPATH

RUN git clone https://github.com/pybind/pybind11.git
RUN (cd pybind11; mkdir build; cd build; cmake -DPYBIND11_PYTHON_VERSION=2.7 ..);
RUN (cd pybind11/build; make -j4 && make install);

WORKDIR /eos
